In [1]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

In [3]:
mydata = pd.read_csv('DMart.csv', sep=',', encoding='ISO-8859-1')
mydata.head()

,Name,Brand,Price,DiscountedPrice,Category,SubCategory,Quantity,Description,BreadCrumbs
0,Premia Badam (Almonds),Premia,451.0,329.0,Grocery,Grocery/Dry Fruits,500 gm,India,Grocery > Grocery/Dry Fruits
1,Premia Badam (Almonds),Premia,109.0,85.0,Grocery,Grocery/Dry Fruits,100 gm,India,Grocery > Grocery/Dry Fruits
2,Premia Badam (Almonds),Premia,202.0,175.0,Grocery,Grocery/Dry Fruits,200 gm,India,Grocery > Grocery/Dry Fruits
3,Nutraj California Almonds (Badam),Nutraj,599.0,349.0,Grocery,Dry Fruits,500 gm,USA,Grocery > Dry Fruits
4,Nutraj California Almonds (Badam),Nutraj,1549.0,659.0,Grocery,Dry Fruits,1 kg,USA,Grocery > Dry Fruits

In [4]:
mydata.values

array([['Premia Badam (Almonds)', 'Premia', 451.0, ..., '500 gm',
        'India', 'Grocery > Grocery/Dry Fruits'],
       ['Premia Badam (Almonds)', 'Premia', 109.0, ..., '100 gm',
        'India', 'Grocery > Grocery/Dry Fruits'],
       ['Premia Badam (Almonds)', 'Premia', 202.0, ..., '200 gm',
        'India', 'Grocery > Grocery/Dry Fruits'],
       ...,
       ['Navneet Youva Long Notebook - Assorted', 'Navneet', 55.0, ...,
        '1 Book',
        'OverviewAttractive colour and designs. Easy to use. Best quality writing paper.- Material : Paper- Ruled Type : Unruled- No.of Pages : 172- Type of Binding : Soft Bound- Size : Regular- Dimension : 27cm x 17 cm x3 cm- Generic Name : NotebookAbout The BrandNavneet Education Limited, is in the business of Educational and children Books Publishing, paper stationery and non-paper stationery products. Since 1959, Navneet has been a dominant player in the field of publishing, with more than 5000 titles. It has emerged as a leading Educational Products and Services Company in India. The company also enjoys leading position in premiere stationery markets Africa, U.S.A. and Europe with now more than 500 Stock Keeping Units, Navneet is one of the largest paper stationery brand in India.',
        'School Supplies > School Needs'],
       ['Navneet Youva Drawing Book - Assorted', 'Navneet', 110.0, ...,
        '1 Book',
        'OverviewDrawing book has attractive cover designs & comes in a big size, for larger drawings & paintings. Easy to use. Thick, premium acid-free paper which does not fade or change shades over time. Paper obtained from sustainable sources. It is ECF pulp based and reduces toxic effluent.Material : PaperRuled Type : PlainNumber of Pages : 36Type of Binding : Wiro BoundSize : 27 cms x 35 cmsDimension : 35 cms x 27.5 cms x 3 cmsAbout the BrandNavneet Education Limited, is in the business of Educational and children&rsquo;s Books Publishing, paper stationery and non-paper stationery products. Since 1959, Navneet has been a dominant player in the field of publishing, with more than 5000 titles. It has emerged as a leading Educational Products and Services Company in India. The company also enjoys leading position in premiere stationery markets in Africa, U.S.A. and Europe with now more than 500 Stock Keeping Units, Navneet is one of the largest paper stationery brand in India.',
        'School Supplies > School Needs'],
       ['Navneet Youva Canvas Board (10x12 Inches)', 'Navneet', 90.0,
        ..., '1 U',
        'OverviewCoated with a double layer of acrylic gesso primer which aids in adhesion and allows proper absorbency of colours and also enhances the brightness. It is acid-free because of which the colours do not spread & retain actual colour for a longer time.Material : CottonType of Binding : Case BoundSize : 10 inches x 12 inchesDimension : 30 cms x 25 cms x 3 cmsAbout the BrandNavneet Education Limited, is in the business of Educational and children&rsquo;s Books Publishing, paper stationery and non-paper stationery products. Since 1959, Navneet has been a dominant player in the field of publishing, with more than 5000 titles. It has emerged as a leading Educational Products and Services Company in India. The company also enjoys leading position in premiere stationery markets in Africa, U.S.A. and Europe with now more than 500 Stock Keeping Units, Navneet is one of the largest paper stationery brand in India.',
        'School Supplies > School Needs']], dtype=object)

In [16]:
mydata = mydata.dropna(subset=["Name"])
data = mydata['Name'].apply(lambda x: [x])
data

0                          [Premia Badam (Almonds)]
1                          [Premia Badam (Almonds)]
2                          [Premia Badam (Almonds)]
3               [Nutraj California Almonds (Badam)]
4               [Nutraj California Almonds (Badam)]
                           ...
5184         [Navneet Youva A4 Notebook - Assorted]
5185    [Navneet Youva Longbook Journal - Assorted]
5186       [Navneet Youva Long Notebook - Assorted]
5187        [Navneet Youva Drawing Book - Assorted]
5188    [Navneet Youva Canvas Board (10x12 Inches)]
Name: Name, Length: 5188, dtype: object

In [17]:
# melakukan proses dataset dan menyimpan nya dalam dataFrame 
from mlxtend.preprocessing import TransactionEncoder
te = TransactionEncoder()

data_encode = te.fit(data).transform(data)

mydata = pd.DataFrame(data_encode, columns=te.columns_)
mydata = mydata.astype(int)
mydata

,24 Mantra Organic Flax Seeds,24 Mantra Organic Green Moong Whole,24 Mantra Organic Jaggery Powder,24 Mantra Organic Jowar Flour,24 Mantra Organic Kabuli Chana,24 Mantra Organic Moong Dal,24 Mantra Organic Peanut,24 Mantra Organic Poha,24 Mantra Organic Ragi Flour,24 Mantra Organic Red Poha,...,Zeel MS201 Men's Raincoat - Blue,Zeel MS201 Men's Raincoat - Light Green,Zeel MS201 Men's Raincoat - Purple,Zeel MS301 Men's Raincoat - Black,Zeel MS301 Men's Raincoat - Grey,Zeel MS301 Men's Raincoat - Navy Blue,Zeel MT212 Men's Raincoat - Navy Blue : Size XXL,Zodiac Comb,Zucchini Green,Zucchini Yellow
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5183,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5184,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5185,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5186,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5187,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [20]:
te = TransactionEncoder()
data_encoded = te.fit(data).transform(data)

In [33]:
# 1Mengimpor library yang diperlukan
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

# Menangani nilai yang hilang jika ada
mydata = mydata.dropna(subset=["Name"])

# Mengubah kolom 'Name' menjadi list dari list
data = mydata['Name'].apply(lambda x: [x])

# Menggunakan TransactionEncoder untuk mengonversi data menjadi format biner
te = TransactionEncoder()
data_encoded = te.fit(data).transform(data)
mydata_encoded = pd.DataFrame(data_encoded, columns=te.columns_).astype(bool)
frequent_itemsets = apriori(mydata_encoded, min_support=0.01, use_colnames=True)  # Menurunkan min_support

# Menghitung aturan asosiasi
if not frequent_itemsets.empty:
    rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1.0)
    print("Aturan Asosiasi yang Ditemukan:")
    print(rules)
else:
    print("Tidak ada itemset yang ditemukan dengan min_support yang diberikan.")

Tidak ada itemset yang ditemukan dengan min_support yang diberikan.